# Genetic-Alpha generated factor 3
import numpy as np
import pandas as pd

def calculate_factor(stock_data):
    # Factor generated by Genetic-Alpha
    # Original expression: ifcondition_e(ts_highday(add(high, low), 3.000), correlation(min(open, high), open, 3.000), close, delay(covariance(open, open, 9.000), 7.000))

    # Calculate basic derived features
    stock_data['returns'] = stock_data['close'] / stock_data['close'].shift(1) - 1
    stock_data['range'] = stock_data['high'] - stock_data['low']
    stock_data['hlc3'] = (stock_data['high'] + stock_data['low'] + stock_data['close']) / 3

    # Implement factor calculation based on genetic programming result
    try:
        factor_value = ifcondition_e(ts_stock_data['high']day(+(stock_data['high'], stock_data['low']), 3.000), correlation(min(stock_data['open'], stock_data['high']), stock_data['open'], 3.000), stock_data['close'], delay(covariance(stock_data['open'], stock_data['open'], 9.000), 7.000))
        # Handle potential NaN and inf values
        factor_value = factor_value.replace([np.inf, -np.inf], np.nan)
        return factor_value
    except Exception as e:
        # Fallback calculation if expression execution fails
        print(f'Factor calculation error: {e}')
        return stock_data['returns']  # Default to returns if error occurs
