# Genetic-Alpha generated factor 10
import numpy as np
import pandas as pd

def calculate_factor(stock_data):
    # Factor generated by Genetic-Alpha
    # Original expression: covariance(ts_lowday(high, 1.000), correlation(high, high, 4.000), 5.000)

    # Calculate basic derived features
    stock_data['returns'] = stock_data['close'] / stock_data['close'].shift(1) - 1
    stock_data['range'] = stock_data['high'] - stock_data['low']
    stock_data['hlc3'] = (stock_data['high'] + stock_data['low'] + stock_data['close']) / 3

    # Implement factor calculation based on genetic programming result
    try:
        factor_value = covariance(ts_stock_data['low']day(stock_data['high'], 1.000), correlation(stock_data['high'], stock_data['high'], 4.000), 5.000)
        # Handle potential NaN and inf values
        factor_value = factor_value.replace([np.inf, -np.inf], np.nan)
        return factor_value
    except Exception as e:
        # Fallback calculation if expression execution fails
        print(f'Factor calculation error: {e}')
        return stock_data['returns']  # Default to returns if error occurs
