# Genetic-Alpha generated factor 6
import numpy as np
import pandas as pd

def calculate_factor(stock_data):
    # Factor generated by Genetic-Alpha
    # Original expression: delta(ifcondition_e(indneutral(high), mul(high, close), open, ts_count(high, close, 1.000)), 4.000)

    # Calculate basic derived features
    stock_data['returns'] = stock_data['close'] / stock_data['close'].shift(1) - 1
    stock_data['range'] = stock_data['high'] - stock_data['low']
    stock_data['hlc3'] = (stock_data['high'] + stock_data['low'] + stock_data['close']) / 3

    # Implement factor calculation based on genetic programming result
    try:
        factor_value = delta(ifcondition_e(indneutral(stock_data['high']), *(stock_data['high'], stock_data['close']), stock_data['open'], ts_count(stock_data['high'], stock_data['close'], 1.000)), 4.000)
        # Handle potential NaN and inf values
        factor_value = factor_value.replace([np.inf, -np.inf], np.nan)
        return factor_value
    except Exception as e:
        # Fallback calculation if expression execution fails
        print(f'Factor calculation error: {e}')
        return stock_data['returns']  # Default to returns if error occurs
