# Genetic-Alpha generated factor 9
import numpy as np
import pandas as pd

def calculate_factor(stock_data):
    # Factor generated by Genetic-Alpha
    # Original expression: ifcondition_e(div(volume, volume), add(low, volume), min(close, high), add(open, volume))

    # Calculate basic derived features
    stock_data['returns'] = stock_data['close'] / stock_data['close'].shift(1) - 1
    stock_data['range'] = stock_data['high'] - stock_data['low']
    stock_data['hlc3'] = (stock_data['high'] + stock_data['low'] + stock_data['close']) / 3

    # Implement factor calculation based on genetic programming result
    try:
        factor_value = ifcondition_e(/(stock_data['volume'], stock_data['volume']), +(stock_data['low'], stock_data['volume']), min(stock_data['close'], stock_data['high']), +(stock_data['open'], stock_data['volume']))
        # Handle potential NaN and inf values
        factor_value = factor_value.replace([np.inf, -np.inf], np.nan)
        return factor_value
    except Exception as e:
        # Fallback calculation if expression execution fails
        print(f'Factor calculation error: {e}')
        return stock_data['returns']  # Default to returns if error occurs
